# Generated by Django 4.1.1 on 2022-09-26 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("searches", "0002_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="author",
        ),
    ]
