# Generated by Django 4.1.1 on 2022-09-27 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("searches", "0004_profile_starrted_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="article",
            new_name="profile",
        ),
    ]
