# Generated by Django 4.1.1 on 2022-09-27 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("searches", "0006_profile_got_skills"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="starrted",
            new_name="star",
        ),
    ]
